name: Deploy website
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: install node-sass
      run: npm install node-sass
    - name: rebuild node-sass
      run: npm rebuild node-sass
    - name: install all package
      run: npm install --unsafe-perm

    - name: build
      run: npm run build && npm run docz:build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.docz/dist
